#!/bin/sh
# See https://docs.docker.com/docker-hub/builds/advanced/
if [ "$DOCKER_TAG" = latest ]
then
    while read python spec tail
    do
        TORCH="${spec%%@*}"
        docker push $DOCKER_REPO:$TORCH-$python
    fi < versions
fi
