name: Test
on:
  push:
    branches:
    - actions-test
  workflow_dispatch:

permissions: {}

env:
  TOP_ENV: test

jobs:
  build-pytorch-wheel:
    runs-on: [self-hosted, ARM64]
    steps:
    - name: shell environment
      run: |
        env | sort
    - name: env context
      run: |
        echo "${{ toJSON(env) }}"
    - name: vars
      run: |
        echo "${{ toJSON(vars) }}"
    - name: github
      run: |
        echo "${{ toJSON(github) }}"
    - name: runner
      run: |
        echo "${{ toJSON(runner) }}"
