name: Test
on:
  push:
    branches:
    - actions-test
  workflow_dispatch:

permissions: {}

env:
  TOP_ENV: test

jobs:
  build-pytorch-wheel:
    runs-on: [self-hosted, ARM64]
    steps:
    - run: |
        env | sort
    - run: |
        echo "${{ toJSON(env) }}"
